coder:
  service:
    type: NodePort
  ingress:
    enable: "true"
    className: nginx
    host: ""
    wildcardHost: ""
  env:
    - name: CODER_TELEMETRY_ENABLE
      value: "false"
    - name: CODER_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          name: coder-db-url
          key: url
    - name: CODER_ACCESS_URL
      value: ""
    - name: CODER_WILDCARD_ACCESS_URL
      value: ""