apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  namespace: {{ .Values.pvc.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: {{ .Values.pv.name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}

