apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.pv.name }}
  capacity:
    storage: {{ .Values.pv.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.pv.path }}

