apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "langfuse-ingress"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 8g
spec:
  ingressClassName: "nginx"
  tls:
    - secretName: langfuse-ssl
      hosts:
        - ""
  rules:
  - host: ""
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: "langfuse-svc"
              port:
                number: 3003
---
  apiVersion: cert-manager.io/v1
  kind: Issuer
  metadata:
    name: letsencrypt-production
  spec:
    acme:
      server: https://acme-v02.api.letsencrypt.org/directory
      email: myemail 
      privateKeySecretRef:
        name: letsencrypt-production
      solvers:
      - http01:
          ingress:
            name: langfuse-ingress
