apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.codeServer.user}}-cs-credentials
  labels:
    {{- include "code-server-charts.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.codeServer.user | quote }}
  password: {{ .Values.codeServer.password | quote }}

