apiVersion: apps/v1
kind: Deployment
metadata:
  name: langfuse-app
spec:
  selector:
    matchLabels:
      app: langfuse-app
  template:
    metadata:
      labels:
        app: langfuse-app
    spec:
      securityContext:
        runAsUser: 1005
        runAsGroup: 2222
        fsGroup: 2222
      containers:
      - name: langfuse-app
        image: ghcr.io/langfuse/langfuse
        env: 
          - name: "DATABASE_USERNAME"
            value: "langfuse"
          - name: "DATABASE_PASSWORD"
            value: password
          - name: "DATABASE_HOST"
            value: db_host
          - name: "DATABASE_PORT"
            value: "5432"
          - name: "DATABASE_NAME"
            value: "langfuse"
          - name: "NEXTAUTH_URL"
            value: "https://langfuse.lqoasis-aut0.aisingapore.net/api/auth"
          - name: "NEXTAUTH_SECRET"
            value: mysecret
          - name: "SALT"
            value: mysalt
          - name: "ENCRYPTION_KEY"
            value: mykey
          - name: "PORT"
            value: "3000"
          - name: HOSTNAME
            value: "0.0.0.0"
          - name: AUTH_DISABLE_USERNAME_PASSWORD
            value: "true"
          - name: AUTH_AZURE_AD_CLIENT_ID
            value: azure_id 
          - name: AUTH_AZURE_AD_CLIENT_SECRET
            value: azure_secret 
          - name: AUTH_AZURE_AD_TENANT_ID
            value: tenant_id 
          - name: NEXT_PUBLIC_SIGN_UP_DISABLED
            value: "false"
          - name: ENABLE_EXPERIMENTAL_FEATURES
            value: "false"
          - name: LANGFUSE_LOG_LEVEL
            value: "debug"
        ports:
          - containerPort: 3000
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /api/public/health
            port: 3000
        readinessProbe:
          httpGet:
            path: /api/public/ready
            port: 3000

