secrets:
  name: mlflow-nginx-server-secrets
  username: mlops
  password: a1s1n9apore
  databaseUri: "sqlite:///polyaxon-v1-data/mlflow.db"
service:
  name: mlflow-nginx-server-svc
  port: 5005
  appName: mlflow-nginx-server
deployment:
  name: mlflow-nginx-server-deployment
  imageName: mlflow
  image: ryzalk/mlflow-nginx-server:0.1.0
  resources:
    memory: "2Gi"
    cpu: "2"
  limits:
    memory: "4Gi"
    cpu: "2"
backup:
  name: mlflow-sqlitedb-backup-job
  schedule: "30 03 * * 0,2,4,6"
  timeoutSec: 60
  imageName: google-cloud-sdk
  image: google/cloud-sdk:slim
  path: mlflow-tracking-server/db-backups
  args:
  - gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS;
    export GCP_PROJECT_ID=$(gcloud config list --format 'value(core.project)');
    gsutil ls -b gs://$GCP_PROJECT_ID-artefacts/$MLFLOW_BACKUP_PATH || gsutil mb -p $GCP_PROJECT_ID -l ASIA-SOUTHEAST1 gs://$GCP_PROJECT_ID-artefacts;
    gsutil cp /polyaxon-v1-data/mlflow.db gs://$GCP_PROJECT_ID-artefacts/$MLFLOW_BACKUP_PATH/$(date +"%d%m%y_%H%M%S")_utc_mlflow.db
persistent:
  volumeName: mlflow-persistent-storage
  mountPath: /polyaxon-v1-data
  volumeClaimName: fstore-rwx-pvc
gcp:
  credentialsName: gcp-imagepullsecrets
  serviceAccount:
    name: gcp-service-account
    secretName: gcp-sa-credentials
    mountPath: /var/secret/cloud.google.com
    yamlName: gcp-service-account.json
