apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.backup.name }}
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.backup.timeoutSec }}
      template:
        spec:
          containers:
          - name: {{ .Values.backup.imageName }}
            image: {{ .Values.backup.image }}
            imagePullPolicy: Always
            command: ["/bin/bash","-c"]
            args:
            {{- range .Values.backup.args }}
            - {{ . }}
            {{- end }}
            volumeMounts:
            - name: {{ .Values.persistent.volumeName }}
              mountPath: {{ .Values.persistent.mountPath }}
            - name: {{ .Values.gcp.serviceAccount.name }}
              mountPath: {{ .Values.gcp.serviceAccount.mountPath }}
              readOnly: true
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: {{ .Values.gcp.serviceAccount.mountPath }}/{{ .Values.gcp.serviceAccount.yamlName }}
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: {{ .Values.gcp.credentialsName }}
          volumes:
          - name: {{ .Values.persistent.volumeName }}
            persistentVolumeClaim:
              claimName: {{ .Values.persistent.volumeClaimName }}
          - name: {{ .Values.gcp.serviceAccount.name }}
            secret:
              secretName: {{ .Values.gcp.serviceAccount.secretName }}
