apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.secrets.name }}
stringData:
  mlflowTrackingUsername: {{ .Values.secrets.username }}
  mlflowTrackingPassword: {{ .Values.secrets.password }}
  databaseUri: {{ .Values.secrets.databaseUri }}

