apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.appName }}
    spec:
      containers:
        - image: {{ .Values.deployment.image }}
          imagePullPolicy: Always
          name: {{ .Values.deployment.imageName }}
          resources:
            requests:
              memory: {{ .Values.deployment.resources.memory }}
              cpu: {{ .Values.deployment.resources.cpu }}
            limits:
              memory: {{ .Values.deployment.limits.memory }}
              cpu: {{ .Values.deployment.limits.cpu }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: {{ .Values.deployment.appName }}
          volumeMounts:
            - name: {{ .Values.persistent.volumeName }}
              mountPath: {{ .Values.persistent.mountPath }}
            - name: {{ .Values.gcp.serviceAccount.name }}
              mountPath: {{ .Values.gcp.serviceAccount.mountPath }}
              readOnly: true
          env:
            - name: MLFLOW_TRACKING_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: mlflowTrackingUsername
            - name: MLFLOW_TRACKING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: mlflowTrackingPassword
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: databaseUri
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: {{ .Values.gcp.serviceAccount.mountPath }}/{{ .Values.gcp.serviceAccount.yamlName }}
      imagePullSecrets:
        - name: {{ .Values.gcp.credentialsName }}
      volumes:
        - name: {{ .Values.persistent.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistent.volumeClaimName }}
        - name: {{ .Values.gcp.serviceAccount.name }}
          secret:
            secretName: {{ .Values.gcp.serviceAccount.secretName }}
