apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.service.appName }}
  type: {{ .Values.service.type }}
