reverseProxy:
  image: "neo4j/helm-charts-reverse-proxy:5.24.1"

  # Name of the kubernetes service. This service should have the ports 7474 and 7687 open.
  # This could be the admin service ex: "standalone-admin" or the loadbalancer service ex: "standalone" created via the neo4j helm chart
  # serviceName , namespace , domain together will form the complete k8s service url. Ex: standalone-admin.default.svc.cluster.local
  # When used against a cluster ensure the service being used is pointing to all the cluster instances.
  # This could be the loadbalancer from neo4j helm chart or the headless service installed via neo4j-headless-service helm chart
  serviceName: "neo4j-lb-neo4j"

  podSecurityContext:
    fsGroupChangePolicy: "OnRootMismatch"

  ingress:
    enabled: true
    annotations: 
      # following annotations are for gke implementation, change accordingly for on-prem
      cert-manager.io/issuer: "letsencrypt-prod" 
    host: ""
    tls:
      enabled: true
      config:
      - secretName: "neo4j-ssl"
        hosts:
          - neo4j.sip-hutchinson-aut0.aisingapore.net # change accordingly to project