reverseProxy:
  image: "neo4j/helm-charts-reverse-proxy:5.24.1"

  # Name of the kubernetes service. This service should have the ports 7474 and 7687 open.
  serviceName: "neo4j-lb-neo4j"

  podSecurityContext:
    fsGroupChangePolicy: "OnRootMismatch"

  ingress:
    enabled: true
    annotations: 
      # following annotations are for gke implementation, change accordingly for on-prem
      cert-manager.io/issuer: "letsencrypt-prod" 
    host: ""
    tls:
      enabled: true
      config:
      - secretName: "neo4j-ssl"
        hosts: []