neo4j:
  # Name of your cluster
  name: "hutchinson-neo4j"
  # Existing secret to use for initial database password
  passwordFromSecret: "neo4j-auth"
  # Neo4j Edition to use (community|enterprise)
  edition: "community"

volumes:
  data:
    mode: "defaultStorageClass"

securityContext:
  fsGroupChangePolicy: "OnRootMismatch"

services:
  neo4j:
    enabled: true
    spec:
      type: NodePort